apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ironfang26/backend
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "admin"
            - name: DB_NAME
              value: "mydb"
            - name: DB_PORT
              value: "3306"
            - name: PORT
              value: "3000"
